### ISSUE TITLE
Open call for better package name

### ISSUE THREAD

**Issue by kevinrue** [kevinrue/iSEEExperimentHub#5]
## Motivation

`iSEEExperimentHub` is a long name, painfully case-sensitive, and includes a visually confusing number of consecutive `E`.

Happy to hear suggestions for a better package name in this thread!

## Prize

The package does not have a logo/sticker yet, but the winning name would be first-in-line for a sticker when the first batch is produced!

**Comment by kevinrue** [comment]
> From Alan O'C on Slack:
> iSEEEHub seems like a decent option but I can 100% guarantee people will forget how many Es to use

**Comment by DarwinAwardWinner** [comment]
If iSEE stands for "Interactive SummarizedExperiment Explorer", then "iSEEExperimentHub" stands for "Interactive SummarizedExperiment Explorer Experiment Hub", which has some redundancy. One option would be to reduce the redundancy and call it "Interactive SummarizedExperiment Exploration Hub", which abbreviates to iSEEHub. Hopefully that still captures the spirit of the package? (As a bonus, it has a nice pronunciation, "icy hub"/"I see hub".)

**Comment by kevinrue** [comment]
I like the thinking. The name iSEEHub crossed my mind at some point, but I didn't have the rationale for it, and I like yours!

Definitely a top candidate while I polish a bit the functionality.

Let's see what else might come up in the meantime ;)

**Comment by kevinrue** [comment]
I was about to rename when I thought that `iSEEhub` (lowercase `h`) would be nicer.

Bits of logic:

- It makes it that tiny bit simpler to type.
- I'm trying to keep iSEE the last package where I used capitalisation, and I strive to make new packages all lowercase (easier to type and to remember). In this case, I just minimise the amount of capitalisation.
- "hub" is a full word itself, which means that there is no need for a capital `H` to act as any sort of acronym.

What do you think about it @DarwinAwardWinner  ?

**Comment by DarwinAwardWinner** [comment]
Looking at existing Bioconductor packages, I see examples of both kinds of capitalization. E.g. S4Vectors, IRanges, DESeq2, GOSemSim vs. Rhtslib, Rsamtools, Rhdf5lib, GEOquery. So I think either way of capitalizing is fine.

**Comment by kevinrue** [comment]
Oh yeah, existing packages have all sorts of name styles. I'll go with `iSEEhub` for the reasons above.
Thanks!

(Now, onto thinking about a hexsticker design :P )

**Comment by kevinrue** [comment]
Renamed in #7
